// Action Types
export const GET_POSTS = 'GET_POSTS'
export const GET_RECENT_POSTS = 'GET_RECENT_POSTS'
export const GET_SINGLE_POST = 'GET_SINGLE_POST'
export const BEGIN_EDIT_SINGLE_POST = 'BEGIN_EDIT_SINGLE_POST'
export const EDIT_SINGLE_POST = 'EDIT_SINGLE_POST'
export const DELETE_SINGLE_POST = 'DELETE_SINGLE_POST'
export const GET_WEATHER_DATA = 'GET_WEATHER_DATA'

