// Action Types
export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_SINGLE_POST = 'GET_SINGLE_POST'
export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS'
export const EDIT_SINGLE_POST = 'EDIT_SINGLE_POST'
export const EDIT_SINGLE_POST_SUCCESS = 'EDIT_SINGLE_POST_SUCCESS'
export const DELETE_SINGLE_POST = 'DELETE_SINGLE_POST'
export const DELETE_SINGLE_POST_SUCCESS ='DELETE_SINGLE_POST_SUCCESS'
export const GET_WEATHER_DATA = 'GET_WEATHER_DATA'
export const GET_WEATHER_DATA_SUCCESS = 'GET_WEATHER_DATA_SUCCESS'

